/**
 * Header + footer + page-number builders for the YUNITE Document Engine.
 *
 * pdfmake renders `header`/`footer` functions on every page, passing the
 * current page number + page count. These build the branded letterhead
 * header strip, the footer copyright + doc ref + page numbers, and the
 * page-number node used inside the footer.
 */

import type { ResolvedOrgIdentity } from '../styles/yunite-document.styles';
import type { DocumentEnvelope } from '../types/document.types';
import { BRAND_COLORS } from '@/lib/services/reports/brand';
import { formatDate, formatDateTime } from './formatting';
import type { Content } from 'pdfmake';

/**
 * The repeating page header: org name + tagline on the left, doc ref + page
 * indicator on the right. Kept compact so the body margin (90pt top) fits it.
 */
export function pageHeader(org: ResolvedOrgIdentity, env: DocumentEnvelope): Content {
  return {
    margin: [40, 20, 40, 0],
    stack: [
      {
        columns: [
          {
            width: '*',
            stack: [
              { text: org.name, style: 'orgName' },
              { text: `${org.tagline} · Reg. ${org.registrationNumber}`, style: 'orgTagline' },
            ],
          },
          {
            width: 'auto',
            stack: [
              { text: env.eyebrow.toUpperCase(), style: 'eyebrow', alignment: 'right' },
              { text: env.documentNumber, style: 'metaValue', alignment: 'right' },
            ],
          },
        ],
      },
      {
        canvas: [
          {
            type: 'rect',
            x: 0, y: 0, w: 515, h: 3,
            color: BRAND_COLORS.navy,
            fillColor: BRAND_COLORS.navy,
          },
        ],
        margin: [0, 6, 0, 0],
      },
    ],
  } as unknown as Content;
}

/**
 * The repeating page footer: copyright + doc ref + auth hash + verify URL +
 * page number. The footer function receives the page node so it can render
 * "Page X of Y".
 */
export function pageFooter(org: ResolvedOrgIdentity, env: DocumentEnvelope): (currentPage: number, pageCount: number) => Content {
  return (currentPage: number, pageCount: number): Content => ({
    margin: [40, 0, 40, 24],
    stack: [
      {
        canvas: [
          {
            type: 'line',
            x1: 0, y1: 0, x2: 515, y2: 0,
            lineWidth: 1,
            lineColor: BRAND_COLORS.green,
          },
        ],
        margin: [0, 0, 0, 4],
      },
      {
        columns: [
          { width: '*', text: org.copyright, style: 'footerCopy' },
          {
            width: 'auto',
            text: `Page ${currentPage} of ${pageCount}`,
            style: 'footerMeta',
            alignment: 'right',
          },
        ],
      },
      {
        columns: [
          { width: '*', text: `Doc Ref: ${env.documentNumber}  ·  Auth Hash: ${env.authHash}`, style: 'footerMeta' },
          { width: 'auto', text: `Generated: ${formatDateTime(env.generatedAt)}`, style: 'footerMeta', alignment: 'right' },
        ],
        margin: [0, 2, 0, 0],
      },
      {
        text: `Verify authenticity: ${env.verifyUrl}`,
        style: 'footerMeta',
        margin: [0, 2, 0, 0],
      },
    ],
  } as unknown as Content);
}

/** The document title block (eyebrow + title + subtitle) placed once at the top of the body. */
export function titleBlock(env: DocumentEnvelope, subtitle?: string): Content {
  return {
    stack: [
      { text: env.eyebrow.toUpperCase(), style: 'eyebrow' },
      { text: env.title, style: 'docTitle', margin: [0, 2, 0, 2] },
      ...(subtitle ? [{ text: subtitle, style: 'subtitle' }] : []),
    ],
    margin: [0, 0, 0, 6],
  } as unknown as Content;
}

/** The meta block: report type / period / date issued / generated by / currency. */
export function metaBlock(env: DocumentEnvelope, org: ResolvedOrgIdentity, extra?: Array<[string, string]>): Content {
  const rows: Array<[string, string]> = [
    ['Period', env.period.label],
    ['Date Issued', formatDate(env.generatedAt)],
    ['Document Ref', env.documentNumber],
    ...(env.issuer ? [['Generated By', `${env.issuer.name} (${env.issuer.role})`] as [string, string]] : []),
    ['Currency', org.currency],
    ...(env.classification ? [['Classification', env.classification] as [string, string]] : []),
    ...(extra ?? []),
  ];
  return {
    stack: rows.map(([label, value]) => ({
      columns: [
        { width: 110, text: label, style: 'metaLabel' },
        { width: '*', text: value, style: 'metaValue' },
      ],
    })),
    margin: [0, 4, 0, 10],
  } as unknown as Content;
}

/** A certification stamp block (text-based, since pdfmake has no SVG stamp). */
export function certificationStamp(env: DocumentEnvelope): Content {
  return {
    stack: [
      { text: 'DOCUMENT CERTIFIED', style: 'metaValue', color: BRAND_COLORS.navy },
      { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 180, y2: 0, lineWidth: 1.5, lineColor: BRAND_COLORS.green }], margin: [0, 2, 0, 2] },
      { text: `Ref: ${env.documentNumber}`, style: 'footerMeta' },
      { text: `Issued: ${formatDate(env.generatedAt)}`, style: 'footerMeta' },
      { text: `Hash: ${env.authHash}`, style: 'footerMeta' },
      { text: `Verify: ${env.verifyUrl}`, style: 'footerMeta' },
    ],
    margin: [0, 14, 0, 6],
    alignment: 'right',
  } as unknown as Content;
}

/** A signature/approval area. */
export function signatureArea(labels: string[] = ['Prepared By', 'Approved By']): Content {
  return {
    columns: labels.map((label) => ({
      width: '*',
      stack: [
        { canvas: [{ type: 'line', x1: 0, y1: 0, x2: 160, y2: 0, lineWidth: 0.5, lineColor: BRAND_COLORS.muted }], margin: [0, 28, 0, 2] },
        { text: label, style: 'footerMeta' },
      ],
    })),
    margin: [0, 10, 0, 10],
    columnGap: 30,
  } as unknown as Content;
}

/** A forced page break. */
export function pageBreak(): Content {
  return { pageBreak: 'after' } as unknown as Content;
}
